### ISSUE TITLE
Update the chapter intros

### ISSUE THREAD

**Issue by larsvilhuber** [amichuda/crress-book#8]
The chapter intros are in _config.yml in the main repo. Can you pull that information and create the chapter intros? 
Alternatively, manually create the chapter intros.

**Comment by amichuda** [comment]
Not sure what you mean? The chapter intros are already in the website. Did
you want something else?

**Comment by larsvilhuber** [comment]
![image](https://user-images.githubusercontent.com/7022712/233731202-eb7b961a-c0a9-4c91-867c-4f78931430ca.png)

**Comment by amichuda** [comment]
Ah good catch. I'm pretty sure the others have chapter intros though.

**Comment by amichuda** [comment]
Closed with 93d7dc70d8c20cdde6842b114dc59cd40334597a
